print("Das ist ein Kalorienzaehler wie myFitnessPal")
print("Bitte Datum im folgenden Format eingeben:dd.mm.jjjj")
date=input()
print("Bitte Kalorien des Fruehstuecks eingeben:")
breakfast=int(input())
print("Bitte Kalorien des Mittagessens eingeben:")
lunch=int(input())
print("Bitte Kalorien des Abendessens eingeben:")
dinner=int(input())
print("Bitte Kalorien der Snacks eingeben")
snacks=int(input())
print("Sie haben heute ("+date+") insgesamt "+str(breakfast+lunch+dinner+snacks)+" Kalorien gegessen.")
